default: &default
  adapter: postgresql
  encoding: unicode
  username: jarivoormedia
  pool: 5
  timeout: 5000
  host: localhost

development:
  <<: *default
  database: benelux_development

test:
  <<: *default
  database: benelux_test

production:
  <<: *default
  database: benelux_production
